// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { dot } from "node:test/reporters";

dotenv.config();

interface DatasourceWithAdapter {
  url?: string;
  shadowDatabaseUrl?: string;
  adapter?: PrismaPg;          // or Unknown
}


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }),
    url: process.env.DATABASE_URL!,
  } as DatasourceWithAdapter,
});
